### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [dearman/activizdotnet#11]

**Comment by dearman** [comment]
I'm still maintaining this version to some extent.  But your usage may vary.  It's not simple to build this, but it's not hard.
It actually works pretty well, if you look through some of my other repos and grab all the glue code.

**Comment by dearman** [comment]
Unfortunately, since this is on github, many of the people that contact me are looking for build support for this, and I'm not in that business.  I ranked this as moderate complexity to build.  I've tried to clean up most of the oddities and document them here in this repo, but it wont change the fact that this is a C/C++ library being bound to some C# wrappers, and all the issues that includes.  Anyone who wants to use this interface to VTK should understand that from the get-go, and have people familiar with such calling standards, and the interop layer.
