### ISSUE TITLE
Can you give more details about how to build dll?

### ISSUE THREAD

**Issue by csumushu** [dearman/activizdotnet#2]

**Comment by dearman** [comment]
Should just follow the typical cmake workflow.  I have uploaded sample CMakeCache.sample files in each repo to illustrate a typical configuration.  I can answer more specific questions.

**Comment by csumushu** [comment]
Thank you, I'll try

**Comment by csumushu** [comment]
Excuse me, I have a question to ask you. Can you direct me? I want to use the Dot function in ActiViz, But the result seems wrong. Can you tell me what's wrong with it? Here's my code。

            double[] v1 = new double[] { 1, 0, 0 };
            double[] v2 = new double[] { 1, 0, 0 };
            IntPtr pv1 = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(double)) * 3);
            IntPtr pv2 = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(double)) * 3);
            Marshal.Copy(v1, 0, pv1, 3);
            Marshal.Copy(v2, 0, pv2, 3);
            double v1v2 = vtkMath.Dot(pv1, pv2);
            Console.WriteLine("Dot：{0}", v1v2);
            Marshal.FreeHGlobal(pv1);
            Marshal.FreeHGlobal(pv2);
            Console.ReadLine();

**Comment by dearman** [comment]
I can take a look.  But I am unfamiliar with that specific function in VTK, so take what I'm saying with a grain of salt.  Also, you may want to check out the mess of code I uploaded to the Activiz-WPF repo.  It was stripped out of an application I was working on, and all functions, although I have not organized it back into a coherent and buildable demo yet.

**Comment by dearman** [comment]
The first thing I notice is that I would not setup as you have.  Look at using the 'pin'.  Pin your input double arrays.

**Comment by dearman** [comment]
https://www.codeproject.com/Articles/38695/UnCommon-C-keywords-A-Look
2. Fixed

Another uncommon keyword is Fixed which can only be used in Unsafe C# code blocks. Fixed statement sets the pointer to be in a fixed memory address so that, it will not be moved to anywhere even if Garbage Collection Thread is invoked.  Let us have a look at the code below: 

```
 int[] a = new int[] { 1, 2, 3 };
fixed (int* pt = a)
{
   int* c = pt;
   MessageBox.Show("Value : " + *c);
   // This will fix the variable totally so that it will
   // not be moved when Garbage collector is invoked. 
}
```

Here, the Pointer c is be assigned the same location as pt. 

Fixed often comes at a cost. It is actually hampers the normal process of Garbage collection. Thus if is good to avoid fixed statement if not actually needed.

**Comment by csumushu** [comment]
Thank you. I don't know why it's wrong, but I've found a solution
http://vtk.1045678.n5.nabble.com/Distance-between-points-tc5725380.html#a5725382
