### ISSUE TITLE
DLL not found Kitware.VTK.vtkRenderingOpenGL2.Unmanaged.dll

### ISSUE THREAD

**Issue by mibotech** [dearman/activizdotnet#6]
Hi,

I have downloaded the latest build and tried to setup a new project but i am getting a dll not found exception. I am not sure if i am missing something but the dll is present in the debug folder.

DllNotFoundException: Unable to load DLL 'Kitware.VTK.vtkRenderingOpenGL2.Unmanaged.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by dearman** [comment]
I would need to know more information about which DLL is missing.  You need to use the Microsoft depends utility to explore where the problem is in the dependency chain.   The most likely cause, is that your build environment does not match mine exactly.  Not all the redistributes are bundled with the Activiz DLL, as this can cause a lot of issues in upstream project use. This project is really not designed for a binary distribution, but a number of people have been able to successfully use it.  Please see my notes on the build environment I used.  Specific issues that have come up before are, Version of VS used, Debug vs Release, x86 vs x64, Intel C++ redist and etc.

**Comment by dearman** [comment]
I uploaded the whole build tree which I am using.  This should include all deps except the VS2013 runtime which you will need.  x86, Debug build.
https://helium.cascadeacoustic.com/downloads/VTK.7z

**Comment by mibo32** [comment]
Hi,
i get the same exception even with your build. Kitware.VTK.vtkRenderingOpenGL2.Unmanaged.dll not found. 
I just create a new win forms application and used the render window control and tried to render a sphere.

**Comment by dearman** [comment]
You realize you are not telling me any helpful information here.  That is not actually the error message, unless you have forgotten to copy the entire dependency tree into the build output directory.  (Ie. merge VTK/bin directory from my download, with the build output of your project, before debugging.  In which case, its not really an issue for this project.)  You need use Dependency Walker, and determine which referenced DLL is actually missing, failing to load, upstream of where the Exception is being generated.

**Comment by dearman** [comment]
The other option, if you don't want to deal with manually copying all the dependencies into the build out, is to add the VTK/bin directory to the Path Environment variable.  

Or as in the screen shots below, you can change the project working directory to VTK/bin

![ss1](https://user-images.githubusercontent.com/2113709/50575803-c82cc980-0db9-11e9-8f19-188e07f546e0.png)
![ss2](https://user-images.githubusercontent.com/2113709/50575802-c82cc980-0db9-11e9-8417-0439e8c653d8.png)
